"""Clean and validate raw POS exports into analysis-ready tables.

Reads data/raw/*.csv, applies standardization and validation, writes
cleaned tables to data/processed/ and a data-quality report to
reports/data_quality_report.md documenting exactly what was fixed.

Cleaning rules:
  * Trim whitespace; normalize location/genre/condition casing to title case
  * Parse mixed date formats (ISO and M/D/YYYY) to ISO dates
  * Strip '$' from money columns and coerce to float
  * Drop exact duplicate rows
  * Enforce referential integrity (sales/inventory product_id must exist
    in products; orphans are dropped and counted)
  * Missing discounts -> 0.00; missing reorder_level -> location median;
    missing release_year/sku left null but counted

Usage:
    python src/clean_data.py
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
PROCESSED = ROOT / "data" / "processed"
REPORTS = ROOT / "reports"


class QualityLog:
    """Collects per-table cleaning metrics for the data-quality report."""

    def __init__(self) -> None:
        self.sections: dict[str, list[str]] = {}

    def add(self, table: str, line: str) -> None:
        self.sections.setdefault(table, []).append(line)

    def render(self) -> str:
        out = [
            "# Data Quality Report",
            "",
            f"Generated by `src/clean_data.py` on {datetime.now():%Y-%m-%d %H:%M}.",
            "",
            "Raw exports arrive with duplicate rows, mixed date formats, casing",
            "drift, currency prefixes, and missing values. This report documents",
            "every correction applied on the way to `data/processed/`.",
            "",
        ]
        for table, lines in self.sections.items():
            out.append(f"## {table}")
            out.append("")
            out.extend(f"- {line}" for line in lines)
            out.append("")
        return "\n".join(out)


def parse_mixed_dates(series: pd.Series) -> pd.Series:
    """Parse a column containing both YYYY-MM-DD and M/D/YYYY strings."""
    s = series.astype(str).str.strip()
    iso = pd.to_datetime(s, format="%Y-%m-%d", errors="coerce")
    us = pd.to_datetime(s, format="%m/%d/%Y", errors="coerce")
    return iso.fillna(us)


def clean_money(series: pd.Series) -> pd.Series:
    return pd.to_numeric(
        series.astype(str).str.strip().str.lstrip("$"), errors="coerce"
    )


def normalize_text(series: pd.Series) -> pd.Series:
    return series.astype(str).str.strip().str.title()


def dedupe(df: pd.DataFrame, table: str, log: QualityLog) -> pd.DataFrame:
    before = len(df)
    df = df.drop_duplicates().reset_index(drop=True)
    log.add(table, f"Removed **{before - len(df)}** exact duplicate rows ({before:,} -> {len(df):,}).")
    return df


def clean_products(log: QualityLog) -> pd.DataFrame:
    df = pd.read_csv(RAW / "products_raw.csv", dtype=str)
    table = "products"
    log.add(table, f"Loaded **{len(df):,}** raw rows.")
    df = dedupe(df, table, log)

    df["artist"] = df["artist"].str.strip()
    df["title"] = df["title"].str.strip()
    df["genre"] = normalize_text(df["genre"])
    # Title-casing breaks genre acronyms/slashes back into canonical labels
    df["genre"] = df["genre"].replace({"Hip-Hop": "Hip-Hop", "Soul/Funk": "Soul/Funk"})
    df["condition"] = normalize_text(df["condition"])
    df["format"] = df["format"].str.strip()

    df["cost"] = clean_money(df["cost"])
    df["price"] = clean_money(df["price"])
    n_price_fixed = int(pd.read_csv(RAW / "products_raw.csv", dtype=str)["price"].str.startswith("$").sum())
    log.add(table, f"Stripped `$` prefixes from **{n_price_fixed}** price values; coerced money columns to numeric.")

    n_year_null = int(df["release_year"].isna().sum())
    n_sku_null = int(df["sku"].isna().sum())
    df["release_year"] = pd.to_numeric(df["release_year"], errors="coerce").astype("Int64")
    log.add(table, f"Left **{n_year_null}** missing release_year and **{n_sku_null}** missing sku as nulls (non-critical fields).")

    bad_price = df["price"].isna() | df["cost"].isna() | (df["price"] <= 0)
    if bad_price.any():
        df = df[~bad_price].reset_index(drop=True)
        log.add(table, f"Dropped **{int(bad_price.sum())}** rows with missing/invalid cost or price.")

    log.add(table, f"Final: **{len(df):,}** clean rows.")
    return df


def clean_sales(products: pd.DataFrame, log: QualityLog) -> pd.DataFrame:
    df = pd.read_csv(RAW / "sales_raw.csv", dtype=str)
    table = "sales"
    log.add(table, f"Loaded **{len(df):,}** raw rows.")
    df = dedupe(df, table, log)

    raw_dates = df["sale_date"].copy()
    df["sale_date"] = parse_mixed_dates(df["sale_date"])
    n_us = int(raw_dates.str.contains("/", na=False).sum())
    n_unparsed = int(df["sale_date"].isna().sum())
    log.add(table, f"Normalized **{n_us}** M/D/YYYY dates to ISO; **{n_unparsed}** unparseable dates dropped.")
    df = df[df["sale_date"].notna()].reset_index(drop=True)

    n_case = int((df["location"] != normalize_text(df["location"])).sum())
    df["location"] = normalize_text(df["location"])
    log.add(table, f"Standardized casing on **{n_case}** location values.")

    df["unit_price"] = clean_money(df["unit_price"])
    n_disc_null = int(df["discount"].isna().sum())
    df["discount"] = clean_money(df["discount"]).fillna(0.0)
    log.add(table, f"Filled **{n_disc_null}** missing discounts with 0.00.")
    df["quantity"] = pd.to_numeric(df["quantity"], errors="coerce").astype("Int64")

    orphans = ~df["product_id"].isin(products["product_id"])
    if orphans.any():
        df = df[~orphans].reset_index(drop=True)
    log.add(table, f"Dropped **{int(orphans.sum())}** rows referencing unknown product_ids.")

    df["net_amount"] = (df["quantity"] * (df["unit_price"] - df["discount"])).round(2)
    log.add(table, f"Derived `net_amount` = quantity x (unit_price - discount).")
    log.add(table, f"Final: **{len(df):,}** clean rows.")
    return df


def clean_inventory(products: pd.DataFrame, log: QualityLog) -> pd.DataFrame:
    df = pd.read_csv(RAW / "inventory_raw.csv", dtype=str)
    table = "inventory"
    log.add(table, f"Loaded **{len(df):,}** raw rows.")
    df = dedupe(df, table, log)

    df["snapshot_date"] = parse_mixed_dates(df["snapshot_date"])
    df["location"] = normalize_text(df["location"])
    for col in ("quantity_on_hand", "days_in_stock"):
        df[col] = pd.to_numeric(df[col], errors="coerce").astype("Int64")

    n_reorder_null = int(df["reorder_level"].isna().sum())
    df["reorder_level"] = pd.to_numeric(df["reorder_level"], errors="coerce")
    df["reorder_level"] = df["reorder_level"].fillna(
        df.groupby("location")["reorder_level"].transform("median")
    ).astype("Int64")
    log.add(table, f"Imputed **{n_reorder_null}** missing reorder_level values with the location median.")

    orphans = ~df["product_id"].isin(products["product_id"])
    if orphans.any():
        df = df[~orphans].reset_index(drop=True)
    log.add(table, f"Dropped **{int(orphans.sum())}** rows referencing unknown product_ids.")
    log.add(table, f"Final: **{len(df):,}** clean rows.")
    return df


def main() -> None:
    PROCESSED.mkdir(parents=True, exist_ok=True)
    REPORTS.mkdir(parents=True, exist_ok=True)
    log = QualityLog()

    products = clean_products(log)
    sales = clean_sales(products, log)
    inventory = clean_inventory(products, log)

    products.to_csv(PROCESSED / "products_clean.csv", index=False)
    sales.assign(sale_date=sales["sale_date"].dt.date).to_csv(PROCESSED / "sales_clean.csv", index=False)
    inventory.assign(snapshot_date=inventory["snapshot_date"].dt.date).to_csv(PROCESSED / "inventory_clean.csv", index=False)

    report_path = REPORTS / "data_quality_report.md"
    report_path.write_text(log.render(), encoding="utf-8")

    print(f"products_clean.csv   {len(products):>7,} rows")
    print(f"sales_clean.csv      {len(sales):>7,} rows")
    print(f"inventory_clean.csv  {len(inventory):>7,} rows")
    print(f"report -> {report_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
